# Generated by Django 4.0.4 on 2022-04-13 23:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
