# Generated by Django 4.0.4 on 2022-04-14 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('description', models.CharField(default='Sem descrição', max_length=150)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
